#!/bin/bash
#SBATCH --job-name=preprocess
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=0-16:00:00
#SBATCH --mem=100gb
#SBATCH -p q64,q36,q24

source /home/${USER}/.bashrc
#conda activate base
#conda activate dns
conda activate tf_gpu


#srun python3 -u update_data.py
#srun python3 -u /home/au569913/DataHandling/notebooks/10-11-21_heat_1vary.py
srun python3 -u /home/au569913/DataHandling/notebooks/22-10-21_make_slices.py
#srun python3 -u /home/au643300/DataHandling/notebooks/26-11-21_plots_new_approch.py
#srun python3 -u /home/au569913/DataHandling/notebooks/frederik/nakamura.py



